import './globals.css'
import { geistMono } from '@repo/fonts/geistMono'
import { geistSans } from '@repo/fonts/geistSans'
import { type Metadata } from 'next'
import { type ReactElement, type ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>): ReactElement {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
